#!/usr/bin/env python

from daemon import runner
import signal

import stromxweb

# implement a service (not only a daemon),
# cf. https://stackoverflow.com/a/30408822

def stopServer(signum, frame):
    stromxweb.stop()

class App():
    def __init__(self):
        self.pidfile_path = '/tmp/stromxweb.pid'
        self.pidfile_timeout = 5
        self.stdin_path = '/dev/null'
        self.stdout_path = '/dev/null'
        self.stderr_path = '/dev/null'

    def run(self):
        signal.signal(signal.SIGTERM, stopServer)
        stromxweb.start('/etc/stromx/stromx.conf')

app = App()
daemon_runner = runner.DaemonRunner(app)
daemon_runner.do_action()
